sudo: required
services:
  - docker

before_install:
  - docker build -t swar23/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true swar23/react-test npm test

after_success:
  - docker build -t swar23/mulit-client ./client
  - docker build -t swar23/mulit-nginx ./nginx
  - docker build -t swar23/mulit-server ./server
  - docker build -t swar23/mulit-worker ./worker
  #log in to docker cli
  - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
  #take those images and push them to docker hub
  - docker push swar23/mulit-client
  - docker push swar23/mulit-nginx
  - docker push swar23/mulit-server
  - docker push swar23/mulit-worker
